//! Canonical, deterministic SimulationCraft input generation.

use std::fmt::Write;

use simshredder_domain::{Item, Profile};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum BuildError {
    #[error("invalid profile: {0}")]
    Invalid(String),
}

pub type Result<T> = std::result::Result<T, BuildError>;

/// Builds the exact UTF-8 bytes that must be passed to SimulationCraft.
pub fn build_input(profile: &Profile) -> Result<Vec<u8>> {
    validate_profile(profile)?;
    let mut output = String::new();
    writeln!(output, "# Generated by SimShredder").expect("String writes cannot fail");
    writeln!(output, "# game_channel=retail_live").expect("String writes cannot fail");
    writeln!(
        output,
        "{}=\"{}\"",
        profile.class.simc_token(),
        profile.name
    )
    .expect("String writes cannot fail");
    writeln!(output, "level={}", profile.level).expect("String writes cannot fail");
    writeln!(output, "race={}", profile.race).expect("String writes cannot fail");
    if let Some(region) = &profile.region {
        writeln!(output, "region={region}").expect("String writes cannot fail");
    }
    if let Some(server) = &profile.server {
        writeln!(output, "server={server}").expect("String writes cannot fail");
    }
    writeln!(output, "role={}", profile.role.simc_token()).expect("String writes cannot fail");
    writeln!(output, "spec={}", profile.specialization).expect("String writes cannot fail");

    for (key, value) in &profile.scalar_options {
        writeln!(output, "{key}={value}").expect("String writes cannot fail");
    }
    for (key, value) in &profile.talents {
        writeln!(output, "{key}={value}").expect("String writes cannot fail");
    }
    if !profile.equipped.is_empty() {
        output.push('\n');
        for item in profile.equipped.values() {
            write_item(&mut output, item);
        }
    }
    if !profile.actions.is_empty() {
        output.push('\n');
        for action in &profile.actions {
            writeln!(output, "{}={}", action.key, action.value).expect("String writes cannot fail");
        }
    }

    output.push_str("\n# SimShredder controlled simulation options\n");
    writeln!(output, "iterations={}", profile.simulation.iterations)
        .expect("String writes cannot fail");
    writeln!(
        output,
        "fixed_time={}",
        u8::from(profile.simulation.fixed_time)
    )
    .expect("String writes cannot fail");
    writeln!(output, "max_time={}", profile.simulation.max_time_seconds)
        .expect("String writes cannot fail");
    writeln!(
        output,
        "vary_combat_length={}",
        profile.simulation.vary_combat_length
    )
    .expect("String writes cannot fail");
    writeln!(
        output,
        "desired_targets={}",
        profile.simulation.desired_targets
    )
    .expect("String writes cannot fail");
    writeln!(output, "fight_style={}", profile.simulation.fight_style)
        .expect("String writes cannot fail");
    writeln!(output, "threads={}", profile.simulation.threads).expect("String writes cannot fail");
    writeln!(output, "seed={}", profile.simulation.seed).expect("String writes cannot fail");
    writeln!(
        output,
        "report_details={}",
        u8::from(profile.simulation.report_details)
    )
    .expect("String writes cannot fail");
    Ok(output.into_bytes())
}

/// Preserves the imported document exactly and appends only deterministic
/// SimShredder-owned overrides. SimulationCraft applies these directives in
/// sequence, so the overlay changes the selected run without rewriting source.
pub fn build_input_overlay(source: &str, original: &Profile, profile: &Profile) -> Result<Vec<u8>> {
    validate_profile(profile)?;
    if original.class != profile.class
        || original.name != profile.name
        || original.level != profile.level
        || original.race != profile.race
        || original.region != profile.region
        || original.server != profile.server
        || original.role != profile.role
        || original.specialization != profile.specialization
    {
        return invalid("actor identity cannot be changed by a run overlay");
    }

    let mut output = source.to_owned();
    if !output.is_empty() && !output.ends_with('\n') && !output.ends_with('\r') {
        output.push('\n');
    }
    output.push_str("\n# SimShredder deterministic run overlay\n");

    // Canonicalize accepted historical aliases such as `role=melee`. Current
    // SimC accepts those inputs but can serialize the actor as `role=auto`,
    // which makes the result contract ambiguous to downstream consumers.
    writeln!(output, "role={}", profile.role.simc_token()).expect("String writes cannot fail");

    for (key, value) in &profile.scalar_options {
        if original.scalar_options.get(key) != Some(value) {
            writeln!(output, "{key}={value}").expect("String writes cannot fail");
        }
    }
    for (key, value) in &profile.talents {
        if original.talents.get(key) != Some(value) {
            writeln!(output, "{key}={value}").expect("String writes cannot fail");
        }
    }
    for (slot, item) in &profile.equipped {
        if original.equipped.get(slot) != Some(item) {
            write_item(&mut output, item);
        }
    }
    if original.actions != profile.actions {
        for action in &profile.actions {
            writeln!(output, "{}={}", action.key, action.value).expect("String writes cannot fail");
        }
    }

    writeln!(output, "iterations={}", profile.simulation.iterations)
        .expect("String writes cannot fail");
    writeln!(
        output,
        "fixed_time={}",
        u8::from(profile.simulation.fixed_time)
    )
    .expect("String writes cannot fail");
    writeln!(output, "max_time={}", profile.simulation.max_time_seconds)
        .expect("String writes cannot fail");
    writeln!(
        output,
        "vary_combat_length={}",
        profile.simulation.vary_combat_length
    )
    .expect("String writes cannot fail");
    writeln!(
        output,
        "desired_targets={}",
        profile.simulation.desired_targets
    )
    .expect("String writes cannot fail");
    writeln!(output, "fight_style={}", profile.simulation.fight_style)
        .expect("String writes cannot fail");
    writeln!(output, "threads={}", profile.simulation.threads).expect("String writes cannot fail");
    writeln!(output, "seed={}", profile.simulation.seed).expect("String writes cannot fail");
    writeln!(
        output,
        "report_details={}",
        u8::from(profile.simulation.report_details)
    )
    .expect("String writes cannot fail");
    Ok(output.into_bytes())
}

fn write_item(output: &mut String, item: &Item) {
    write!(output, "{}=,id={}", item.slot.simc_token(), item.id)
        .expect("String writes cannot fail");
    for (key, value) in &item.options {
        write!(output, ",{key}={value}").expect("String writes cannot fail");
    }
    output.push('\n');
}

fn validate_profile(profile: &Profile) -> Result<()> {
    if profile.name.is_empty()
        || profile.name.len() > 128
        || profile
            .name
            .chars()
            .any(|character| character.is_control() || matches!(character, '"' | '\\'))
    {
        return invalid("player name is unsafe");
    }
    for (label, value) in [
        ("race", profile.race.as_str()),
        ("specialization", profile.specialization.as_str()),
    ] {
        validate_token(label, value)?;
    }
    if let Some(region) = &profile.region {
        validate_token("region", region)?;
    }
    if let Some(server) = &profile.server {
        validate_token("server", server)?;
    }
    if profile.level == 0 || profile.level > 100 {
        return invalid("level is outside the supported range");
    }
    let simulation = &profile.simulation;
    if simulation.iterations == 0
        || simulation.iterations > 10_000_000
        || simulation.max_time_seconds == 0
        || simulation.max_time_seconds > 3_600
        || !simulation.vary_combat_length.is_finite()
        || !(0.0..=1.0).contains(&simulation.vary_combat_length)
        || simulation.desired_targets == 0
        || simulation.desired_targets > 40
        || simulation.threads == 0
        || simulation.threads > 256
        || simulation.seed == 0
    {
        return invalid("simulation options are outside the supported range");
    }
    if !matches!(
        simulation.fight_style.as_str(),
        "Patchwerk"
            | "CastingPatchwerk"
            | "HecticAddCleave"
            | "DungeonSlice"
            | "LightMovement"
            | "HeavyMovement"
            | "HelterSkelter"
            | "CleaveAdd"
            | "Beastlord"
    ) {
        return invalid("fight_style is unsupported");
    }
    for (key, value) in &profile.scalar_options {
        if !matches!(
            key.as_str(),
            "position"
                | "professions"
                | "loot_spec"
                | "zandalari_loa"
                | "flask"
                | "food"
                | "augmentation"
                | "potion"
                | "temporary_enchant"
                | "load_default_gear"
                | "source"
                | "default_actions"
                | "timeofday"
                | "warlock.default_pet"
                | "target_error"
                | "target_level"
                | "target_race"
                | "default_world_lag"
                | "default_world_lag_stddev"
                | "skill"
                | "optimal_raid"
                | "override.bloodlust"
                | "bloodlust_time"
                | "bloodlust_percent"
                | "report_pets_separately"
                | "override.arcane_intellect"
                | "override.battle_shout"
                | "override.mark_of_the_wild"
                | "override.power_word_fortitude"
                | "override.chaos_brand"
                | "override.mystic_touch"
                | "override.windfury_totem"
                | "override.hunters_mark"
                | "override.bleeding"
                | "external_buffs.power_infusion"
                | "external_buffs.blessing_of_summer"
                | "external_buffs.blessing_of_autumn"
                | "external_buffs.blessing_of_winter"
                | "external_buffs.blessing_of_spring"
                | "report_rng"
                | "full_damage_sources_chart"
                | "buff_uptime_timeline"
                | "buff_stack_uptime_timeline"
                | "reaction_time"
                | "queue_lag"
                | "queue_lag_stddev"
                | "gcd_lag"
                | "gcd_lag_stddev"
                | "channel_lag"
                | "channel_lag_stddev"
                | "travel_variance"
                | "enemy_initial_health_percentage"
                | "enemy_death_pct"
        ) && !key.starts_with("midnight.")
        {
            return invalid(format!("unsupported scalar option: {key}"));
        }
        validate_value(key, value)?;
    }
    for (key, value) in &profile.talents {
        if !matches!(
            key.as_str(),
            "talents" | "class_talents" | "spec_talents" | "hero_talents" | "omnium_talents"
        ) {
            return invalid(format!("unsupported talent option: {key}"));
        }
        validate_value(key, value)?;
    }
    for (slot, item) in &profile.equipped {
        if slot != &item.slot || item.id == 0 {
            return invalid("equipped item identity is inconsistent");
        }
        validate_item(item)?;
    }
    for action in &profile.actions {
        if !action.key.starts_with("actions")
            || action.key.len() > 128
            || action.value.is_empty()
            || action.value.len() > 16 * 1024
            || action.key.chars().any(|character| {
                !(character.is_ascii_lowercase()
                    || character.is_ascii_digit()
                    || matches!(character, '_' | '.' | '+'))
            })
            || action.value.chars().any(|character| character.is_control())
        {
            return invalid("action directive is unsafe");
        }
    }
    Ok(())
}

fn validate_item(item: &Item) -> Result<()> {
    for (key, value) in &item.options {
        if key.is_empty()
            || key.len() > 128
            || !key.chars().all(|character| {
                character.is_ascii_lowercase()
                    || character.is_ascii_digit()
                    || matches!(character, '_' | '.')
            })
        {
            return invalid(format!("unsafe item option: {key}"));
        }
        validate_value(key, value)?;
    }
    Ok(())
}

fn validate_token(label: &str, value: &str) -> Result<()> {
    if value.is_empty()
        || value.len() > 512
        || !value
            .chars()
            .all(|character| character.is_alphanumeric() || matches!(character, '_' | '-' | '.'))
    {
        return invalid(format!("{label} is not a safe token"));
    }
    Ok(())
}

fn validate_value(label: &str, value: &str) -> Result<()> {
    if value.is_empty()
        || value.len() > 4096
        || !value.chars().all(|character| {
            character.is_alphanumeric()
                || matches!(character, '_' | '-' | '.' | '/' | ':' | '+' | '%' | '@')
                || character == '='
        })
    {
        return invalid(format!("{label} contains unsupported characters"));
    }
    Ok(())
}

fn invalid<T>(message: impl Into<String>) -> Result<T> {
    Err(BuildError::Invalid(message.into()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use profile_parser::parse_simc_file;
    use simshredder_domain::GearSlot;

    #[test]
    fn same_profile_always_produces_the_same_bytes() {
        let profile = parse_simc_file(
            "warrior=Stable\nlevel=90\nrace=orc\nrole=attack\nspec=fury\nload_default_gear=1\n",
        )
        .unwrap();
        assert_eq!(
            build_input(&profile).unwrap(),
            build_input(&profile).unwrap()
        );
    }

    #[test]
    fn overlay_keeps_source_exact_and_emits_only_changed_owned_fields() {
        let source = "# 유니코드\r\nwarrior=\"Stable Name\"\r\nlevel=90\r\nrace=orc\r\nrole=attack\r\nspec=fury\r\nunknown_future=1";
        let original = parse_simc_file(source).unwrap();
        let mut changed = original.clone();
        changed.simulation.iterations = 4321;
        changed
            .scalar_options
            .insert("optimal_raid".into(), "0".into());
        let first = build_input_overlay(source, &original, &changed).unwrap();
        let second = build_input_overlay(source, &original, &changed).unwrap();
        assert_eq!(first, second);
        assert!(first.starts_with(source.as_bytes()));
        let generated = String::from_utf8(first).unwrap();
        assert!(generated.contains("\noptimal_raid=0\n"));
        assert!(generated.contains("\niterations=4321\n"));
        assert!(generated.contains("\nrole=attack\n"));
        assert_eq!(generated.matches("unknown_future=1").count(), 1);
    }

    #[test]
    fn overlay_canonicalizes_a_supported_dps_role_alias() {
        let source = "rogue=Alias\nlevel=90\nrace=void_elf\nrole=melee\nspec=subtlety\n";
        let profile = parse_simc_file(source).unwrap();
        let generated =
            String::from_utf8(build_input_overlay(source, &profile, &profile).unwrap()).unwrap();

        assert!(generated.starts_with(source));
        assert!(generated.contains("# SimShredder deterministic run overlay\nrole=attack\n"));
    }

    #[test]
    fn defense_in_depth_rejects_injected_action_lines() {
        let mut profile = parse_simc_file(
            "warrior=Stable\nlevel=90\nrace=orc\nrole=attack\nspec=fury\nload_default_gear=1\n",
        )
        .unwrap();
        profile.actions.push(simshredder_domain::ActionDirective {
            key: "actions".into(),
            value: "auto_attack\njson2=/tmp/stolen".into(),
        });
        assert!(build_input(&profile).is_err());
    }

    #[test]
    fn every_gear_slot_has_a_stable_token() {
        let slots = [
            GearSlot::Head,
            GearSlot::Neck,
            GearSlot::Shoulders,
            GearSlot::Back,
            GearSlot::Chest,
            GearSlot::Shirt,
            GearSlot::Tabard,
            GearSlot::Wrists,
            GearSlot::Hands,
            GearSlot::Waist,
            GearSlot::Legs,
            GearSlot::Feet,
            GearSlot::Finger1,
            GearSlot::Finger2,
            GearSlot::Trinket1,
            GearSlot::Trinket2,
            GearSlot::MainHand,
            GearSlot::OffHand,
        ];
        assert_eq!(slots.len(), 18);
        assert_eq!(slots[0].simc_token(), "head");
        assert_eq!(slots[17].simc_token(), "off_hand");
    }
}
