//! Canonical, deterministic SimulationCraft input generation.

use std::fmt::Write;

use simshredder_domain::{Item, Profile};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum BuildError {
    #[error("invalid profile: {0}")]
    Invalid(String),
}

pub type Result<T> = std::result::Result<T, BuildError>;

/// Builds the exact UTF-8 bytes that must be passed to SimulationCraft.
pub fn build_input(profile: &Profile) -> Result<Vec<u8>> {
    validate_profile(profile)?;
    let mut output = String::new();
    writeln!(output, "# Generated by SimShredder").expect("String writes cannot fail");
    writeln!(output, "# game_channel=retail_live").expect("String writes cannot fail");
    writeln!(
        output,
        "{}=\"{}\"",
        profile.class.simc_token(),
        profile.name
    )
    .expect("String writes cannot fail");
    writeln!(output, "level={}", profile.level).expect("String writes cannot fail");
    writeln!(output, "race={}", profile.race).expect("String writes cannot fail");
    if let Some(region) = &profile.region {
        writeln!(output, "region={region}").expect("String writes cannot fail");
    }
    if let Some(server) = &profile.server {
        writeln!(output, "server={server}").expect("String writes cannot fail");
    }
    writeln!(output, "role={}", profile.role.simc_token()).expect("String writes cannot fail");
    writeln!(output, "spec={}", profile.specialization).expect("String writes cannot fail");

    for (key, value) in &profile.scalar_options {
        writeln!(output, "{key}={value}").expect("String writes cannot fail");
    }
    for (key, value) in &profile.talents {
        writeln!(output, "{key}={value}").expect("String writes cannot fail");
    }
    if !profile.equipped.is_empty() {
        output.push('\n');
        for item in profile.equipped.values() {
            write_item(&mut output, item);
        }
    }
    if !profile.actions.is_empty() {
        output.push('\n');
        for action in &profile.actions {
            writeln!(output, "{}={}", action.key, action.value).expect("String writes cannot fail");
        }
    }

    output.push_str("\n# SimShredder controlled simulation options\n");
    writeln!(output, "iterations={}", profile.simulation.iterations)
        .expect("String writes cannot fail");
    writeln!(
        output,
        "fixed_time={}",
        u8::from(profile.simulation.fixed_time)
    )
    .expect("String writes cannot fail");
    writeln!(output, "max_time={}", profile.simulation.max_time_seconds)
        .expect("String writes cannot fail");
    writeln!(
        output,
        "vary_combat_length={}",
        profile.simulation.vary_combat_length
    )
    .expect("String writes cannot fail");
    writeln!(
        output,
        "desired_targets={}",
        profile.simulation.desired_targets
    )
    .expect("String writes cannot fail");
    writeln!(output, "fight_style={}", profile.simulation.fight_style)
        .expect("String writes cannot fail");
    writeln!(output, "threads={}", profile.simulation.threads).expect("String writes cannot fail");
    writeln!(output, "seed={}", profile.simulation.seed).expect("String writes cannot fail");
    writeln!(
        output,
        "report_details={}",
        u8::from(profile.simulation.report_details)
    )
    .expect("String writes cannot fail");
    Ok(output.into_bytes())
}

fn write_item(output: &mut String, item: &Item) {
    write!(output, "{}=,id={}", item.slot.simc_token(), item.id)
        .expect("String writes cannot fail");
    for (key, value) in &item.options {
        write!(output, ",{key}={value}").expect("String writes cannot fail");
    }
    output.push('\n');
}

fn validate_profile(profile: &Profile) -> Result<()> {
    if profile.name.is_empty()
        || profile.name.len() > 64
        || !profile
            .name
            .chars()
            .all(|character| character.is_alphanumeric() || matches!(character, '-' | '\''))
    {
        return invalid("player name is unsafe");
    }
    for (label, value) in [
        ("race", profile.race.as_str()),
        ("specialization", profile.specialization.as_str()),
    ] {
        validate_token(label, value)?;
    }
    if let Some(region) = &profile.region {
        validate_token("region", region)?;
    }
    if let Some(server) = &profile.server {
        validate_token("server", server)?;
    }
    if profile.level == 0 || profile.level > 100 {
        return invalid("level is outside the supported range");
    }
    let simulation = &profile.simulation;
    if simulation.iterations == 0
        || simulation.iterations > 10_000_000
        || simulation.max_time_seconds == 0
        || simulation.max_time_seconds > 3_600
        || !simulation.vary_combat_length.is_finite()
        || !(0.0..=1.0).contains(&simulation.vary_combat_length)
        || simulation.desired_targets == 0
        || simulation.desired_targets > 40
        || simulation.threads == 0
        || simulation.threads > 256
        || simulation.seed == 0
    {
        return invalid("simulation options are outside the supported range");
    }
    if !matches!(
        simulation.fight_style.as_str(),
        "Patchwerk" | "HecticAddCleave" | "DungeonSlice" | "LightMovement" | "HeavyMovement"
    ) {
        return invalid("fight_style is unsupported");
    }
    for (key, value) in &profile.scalar_options {
        if !matches!(
            key.as_str(),
            "position"
                | "professions"
                | "loot_spec"
                | "zandalari_loa"
                | "flask"
                | "food"
                | "augmentation"
                | "potion"
                | "temporary_enchant"
                | "load_default_gear"
                | "source"
                | "default_actions"
        ) {
            return invalid(format!("unsupported scalar option: {key}"));
        }
        validate_value(key, value)?;
    }
    for (key, value) in &profile.talents {
        if !matches!(
            key.as_str(),
            "talents" | "class_talents" | "spec_talents" | "hero_talents" | "omnium_talents"
        ) {
            return invalid(format!("unsupported talent option: {key}"));
        }
        validate_value(key, value)?;
    }
    for (slot, item) in &profile.equipped {
        if slot != &item.slot || item.id == 0 {
            return invalid("equipped item identity is inconsistent");
        }
        validate_item(item)?;
    }
    for action in &profile.actions {
        if !action.key.starts_with("actions")
            || action.key.len() > 128
            || action.value.is_empty()
            || action.value.len() > 16 * 1024
            || action.key.chars().any(|character| {
                !(character.is_ascii_lowercase()
                    || character.is_ascii_digit()
                    || matches!(character, '_' | '.' | '+'))
            })
            || action.value.chars().any(|character| character.is_control())
        {
            return invalid("action directive is unsafe");
        }
    }
    Ok(())
}

fn validate_item(item: &Item) -> Result<()> {
    for (key, value) in &item.options {
        if !matches!(
            key.as_str(),
            "enchant_id"
                | "gem_id"
                | "bonus_id"
                | "gem_bonus_id"
                | "crafted_stats"
                | "crafting_quality"
                | "drop_level"
                | "content_tuning"
                | "redirected_base_stats"
                | "titan_disc_id"
                | "ilevel"
        ) {
            return invalid(format!("unsupported item option: {key}"));
        }
        validate_value(key, value)?;
    }
    Ok(())
}

fn validate_token(label: &str, value: &str) -> Result<()> {
    if value.is_empty()
        || value.len() > 512
        || !value
            .chars()
            .all(|character| character.is_alphanumeric() || matches!(character, '_' | '-' | '.'))
    {
        return invalid(format!("{label} is not a safe token"));
    }
    Ok(())
}

fn validate_value(label: &str, value: &str) -> Result<()> {
    if value.is_empty()
        || value.len() > 4096
        || !value.chars().all(|character| {
            character.is_alphanumeric()
                || matches!(character, '_' | '-' | '.' | '/' | ':' | '+' | '%' | '@')
                || character == '='
        })
    {
        return invalid(format!("{label} contains unsupported characters"));
    }
    Ok(())
}

fn invalid<T>(message: impl Into<String>) -> Result<T> {
    Err(BuildError::Invalid(message.into()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use profile_parser::parse_simc_file;
    use simshredder_domain::GearSlot;

    #[test]
    fn same_profile_always_produces_the_same_bytes() {
        let profile = parse_simc_file(
            "warrior=Stable\nlevel=90\nrace=orc\nrole=attack\nspec=fury\nload_default_gear=1\n",
        )
        .unwrap();
        assert_eq!(
            build_input(&profile).unwrap(),
            build_input(&profile).unwrap()
        );
    }

    #[test]
    fn defense_in_depth_rejects_injected_action_lines() {
        let mut profile = parse_simc_file(
            "warrior=Stable\nlevel=90\nrace=orc\nrole=attack\nspec=fury\nload_default_gear=1\n",
        )
        .unwrap();
        profile.actions.push(simshredder_domain::ActionDirective {
            key: "actions".into(),
            value: "auto_attack\njson2=/tmp/stolen".into(),
        });
        assert!(build_input(&profile).is_err());
    }

    #[test]
    fn every_gear_slot_has_a_stable_token() {
        let slots = [
            GearSlot::Head,
            GearSlot::Neck,
            GearSlot::Shoulders,
            GearSlot::Back,
            GearSlot::Chest,
            GearSlot::Shirt,
            GearSlot::Tabard,
            GearSlot::Wrists,
            GearSlot::Hands,
            GearSlot::Waist,
            GearSlot::Legs,
            GearSlot::Feet,
            GearSlot::Finger1,
            GearSlot::Finger2,
            GearSlot::Trinket1,
            GearSlot::Trinket2,
            GearSlot::MainHand,
            GearSlot::OffHand,
        ];
        assert_eq!(slots.len(), 18);
        assert_eq!(slots[0].simc_token(), "head");
        assert_eq!(slots[17].simc_token(), "off_hand");
    }
}
