import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import axe from "axe-core";
import { beforeEach, describe, expect, it, vi } from "vitest";
import i18n, { resources } from "./i18n";
import { App } from "./App";
import type { JobView } from "./quick";
import { formatRuntimeError } from "./runtime";
import type { TopGearSessionView } from "./topGear";

const { mockInvoke, mockOpen } = vi.hoisted(() => ({ mockInvoke: vi.fn(), mockOpen: vi.fn() }));

vi.mock("@tauri-apps/api/core", () => ({ invoke: mockInvoke }));
vi.mock("@tauri-apps/plugin-dialog", () => ({ open: mockOpen }));
vi.mock("echarts/core", () => ({
  use: vi.fn(),
  init: () => ({ setOption: vi.fn(), resize: vi.fn(), dispose: vi.fn() }),
}));
vi.mock("echarts/charts", () => ({ BarChart: {} }));
vi.mock("echarts/components", () => ({ GridComponent: {}, TooltipComponent: {} }));
vi.mock("echarts/renderers", () => ({ CanvasRenderer: {} }));

const missingRuntime = {
  state: "missing",
  active: null,
  activeDataDate: null,
  installed: [],
  availableVersion: "1210-01",
  availableBuild: "3487fce",
  availableConfirmed: true,
  updateAvailable: false,
  diagnostic: null,
} as const;

const readyRuntime = {
  ...missingRuntime,
  state: "ready",
  activeDataDate: "2026-08-25",
  active: {
    id: "1210-01-3487fce",
    simcVersion: "1210-01",
    build: "3487fce",
    gameVersion: "12.1.0.69465",
    channel: "live",
    executableSha256: "a".repeat(64),
    installedAtUnixSeconds: 1,
  },
  installed: [],
} as const;

let runtimeStatusResult: unknown = missingRuntime;
let recoveredQuickJobs: JobView[] = [];
let recoveredTopGearSessions: TopGearSessionView[] = [];

const emptyIconStatus = { budgetBytes: 268435456, usedBytes: 0, iconCount: 0, mappingCount: 0, remoteProviderEnabled: false } as const;
let iconStatus: { budgetBytes: number; usedBytes: number; iconCount: number; mappingCount: number; remoteProviderEnabled: boolean } = emptyIconStatus;

const defaultStoragePaths = {
  configRoot: "/Users/test/Library/Application Support/SimShredder",
  workspace: "/Users/test/Library/Application Support/SimShredder/workspace",
  simulationcraft: "/Users/test/Library/Application Support/SimShredder/simulationcraft",
  icons: "/Users/test/Library/Application Support/SimShredder/icons",
  exports: "/Users/test/Documents/SimShredder Exports",
  defaultWorkspace: "/Users/test/Library/Application Support/SimShredder/workspace",
  defaultSimulationcraft: "/Users/test/Library/Application Support/SimShredder/simulationcraft",
  defaultIcons: "/Users/test/Library/Application Support/SimShredder/icons",
  defaultExports: "/Users/test/Documents/SimShredder Exports",
} as const;
let storagePaths = { ...defaultStoragePaths };
let storedProfiles: Array<{
  id: string;
  identity: { region: string | null; realm: string | null; characterName: string };
  displayName: string;
  class: string;
  specialization: string;
  favorite: boolean;
  inputSource: "addonExport" | "simcFile" | "armory";
  request: ReturnType<typeof import("./quick").defaultQuickRequest>;
  capturedAtUnixSeconds: number;
  previousInputAvailable: boolean;
  armoryRefresh: { available: boolean; reason: string };
}> = [];

const prepared = {
  profile: { name: "Core", class: "warrior", specialization: "fury", race: "orc", role: "attack", level: 90, equippedItems: 0, bagItems: 0, talents: [{ name: "talents", value: "CgEAAAAAAAA" }], warnings: [], inputCompatibility: { supportedEditable: 6, preservedNotEditable: 1, executionBlocked: 0, diagnostics: [{ line: 7, key: "raid_events", category: "preservedNotEditable", reason: "preserved exactly and delegated to SimulationCraft" }] } },
  generatedInput: "# Generated by SimShredder\nwarrior=Core\niterations=10000\n",
  threads: 4,
  profilesetWorkThreads: 2,
} as const;

const succeededJob: JobView = {
  id: 7,
  state: "succeeded",
  cancelRequested: false,
  failure: null,
  succeededBatches: 1,
  pendingBatches: 0,
  attempts: [{ id: 8, sequence: 1, state: "succeeded", startedUnixMillis: 1_788_000_000_000, finishedUnixMillis: 1_788_000_030_000, failure: null, cacheHit: false, stdoutLogTruncated: false, stderrLogTruncated: false }],
  createdUnixMillis: 1_788_000_000_000,
  updatedUnixMillis: 1_788_000_030_000,
  cpuPreset: "balanced",
  profile: { name: "Core", class: "warrior", specialization: "fury" },
  settings: { iterations: 10_000, maxTimeSeconds: 300, desiredTargets: 1, fightStyle: "Patchwerk", threads: 4 },
  recentDiagnostics: [],
};

const topGearPrepared = {
  profileName: "Core",
  ruleRevision: "12.1.0-69465-v1",
  ruleSource: "Manual input contract",
  rawCombinations: 2,
  validCombinations: 2,
  executionCount: 4,
  finalistCount: 2,
  estimated: false,
  rejections: { dominatedVariants: 0, socketLimit: 0, enchantSlot: 0, uniqueEquipped: 0, embellishmentLimit: 0, weaponConstraint: 0, budget: 0, symmetricDuplicate: 0, minimumSetBonus: 0, catalystLimit: 0, enhancementPolicy: 0 },
  generatedInput: "warrior=Core\nprofileset.0123abcd=default_actions=1\n",
  variants: [
    { key: "worn-head-154029", sourceItemId: 154029, slot: "head", displayName: "Worn Helm", rank: 0, gemIds: [], enchantId: null, simcOptions: {}, cost: {}, actions: [], uniqueGroups: [], setGroups: [], weaponKind: "none", embellishment: false, catalyst: false, enabled: true, changed: false },
    { key: "bag-head-154030", sourceItemId: 154030, slot: "head", displayName: "Candidate Helm", rank: 0, gemIds: [], enchantId: null, simcOptions: {}, cost: {}, actions: [], uniqueGroups: [], setGroups: [], weaponKind: "none", embellishment: false, catalyst: false, enabled: true, changed: true },
    { key: "manual-head-154031-1", sourceItemId: 154031, slot: "head", displayName: "Manual Helm", rank: 0, gemIds: [], enchantId: null, simcOptions: {}, cost: {}, actions: [], uniqueGroups: [], setGroups: [], weaponKind: "none", embellishment: false, catalyst: false, enabled: false, changed: true },
    { key: "worn-trinket1-1001", sourceItemId: 1001, slot: "trinket1", displayName: "First Worn Trinket", rank: 0, gemIds: [], enchantId: null, simcOptions: {}, cost: {}, actions: [], uniqueGroups: [], setGroups: [], weaponKind: "none", embellishment: false, catalyst: false, enabled: true, changed: false },
    { key: "worn-trinket2-1002", sourceItemId: 1002, slot: "trinket2", displayName: "Second Worn Trinket", rank: 0, gemIds: [], enchantId: null, simcOptions: {}, cost: {}, actions: [], uniqueGroups: [], setGroups: [], weaponKind: "none", embellishment: false, catalyst: false, enabled: true, changed: false },
    { key: "bag-trinket1-2001", sourceItemId: 2001, slot: "trinket1", displayName: "Candidate Trinket", rank: 0, gemIds: [], enchantId: null, simcOptions: { ilevel: "334" }, cost: {}, actions: [], uniqueGroups: [], setGroups: [], weaponKind: "none", embellishment: false, catalyst: false, enabled: true, changed: true },
  ],
  talentLoadouts: [
    { key: "active", label: "Active", option: "talents", value: "ACTIVE", changed: false, enabled: true },
    { key: "saved-0", label: "Dungeon", option: "talents", value: "SAVED", changed: true, enabled: false },
  ],
  profileOptions: {
    food: [{ key: "active-food", label: "Active", option: "food", value: "", changed: false, enabled: true }],
    omnium_talents: [{ key: "active-omnium", label: "Active", option: "omnium_talents", value: "", changed: false, enabled: true }],
  },
  loadouts: [],
  detectedBalances: {},
} as const;

const topGearSession = (stage: "low_precision" | "medium_precision" | "high_precision" | "complete"): TopGearSessionView => ({
  id: "tg-test",
  stage,
  currentJob: succeededJob,
  lowJobId: 7,
  mediumJobId: stage === "low_precision" ? null : 8,
  highJobId: stage === "high_precision" || stage === "complete" ? 9 : null,
  actionJobId: null,
  completedExecutions: stage === "low_precision" ? 2 : 4,
  totalExecutions: 4,
  canAdvance: false,
  pipelineFailure: null,
  createdUnixMillis: 1_788_000_000_000,
});

const topGearResultFixture = {
  sessionId: "tg-test",
  baselineKey: "baseline",
  ruleRevision: "12.1.0-69465-v1",
  gameBuild: 69465,
  upgradeMetadata: null,
  upgradeMetadataConfirmed: false,
  ranked: [
    { loadout: { key: "winner", items: { head: topGearPrepared.variants[1] }, cost: { crest: 5 }, changedSlots: 1, changedOptions: 0, talent: { key: "active", label: "Active", option: "talents", value: "ACTIVE", changed: false, enabled: true }, profileOptions: {} }, mean: 123500, meanError: 50, delta: 500, combinedError: 70, equivalentToBaseline: false, paretoOptimal: true, rank: 1 },
    { loadout: { key: "baseline", items: { head: topGearPrepared.variants[0] }, cost: {}, changedSlots: 0, changedOptions: 0, talent: { key: "active", label: "Active", option: "talents", value: "ACTIVE", changed: false, enabled: true }, profileOptions: {} }, mean: 123000, meanError: 50, delta: 0, combinedError: 70, equivalentToBaseline: true, paretoOptimal: false, rank: 2 },
  ],
  lowJobId: 7,
  mediumJobId: 8,
  highJobId: 9,
  actionJobId: null,
  actionPlan: [],
  estimated: false,
  finalGeneratedInput: "warrior=Core\nprofileset.winner=head=,id=154029\n",
  runtime: { simc_version: "1210-01", git_revision: "3487fce", game_version: "12.1.0.69465", game_build: 69465, channel: "live" },
  budget: { balances: { crest: 10 }, reserves: { crest: 2 }, confirmedAtUnixSeconds: 1 },
  enhancementPolicy: "max_potential",
} as const;

const quickResultFixture = {
  jobId: 7,
  result: {
    schema_version: 2,
    report_version: "2.0.0",
    runtime: { simc_version: "1210-01", git_revision: "3487fce", game_version: "12.1.0.69465", game_build: 69465, channel: "live" },
    player: { name: "Core", race: "Orc", role: "attack", specialization: "Fury" },
    options: { iterations: 10000, threads: 4, seed: 1, max_time_seconds: 300, desired_targets: 1, fight_style: "Patchwerk" },
    primary_metric: { name: "DPS", mean: 123456.7, mean_error: 120.2, standard_deviation: 500, minimum: 120000, maximum: 126000, median: 123400 },
    actions: [{ id: 184367, name: "Rampage", internal_name: "rampage", school: "physical", executes: 24.5, amount_per_fight: 1234567, metric_per_second: 45678.9, share: 0.37 }],
    buffs: [{ id: 184362, name: "Enrage", internal_name: "enrage", uptime_percent: 82.4, benefit_percent: 91.2, starts: 18 }],
    resources: [{ name: "rage", spent_per_fight: 1200, overflow_per_fight: 18, remaining_per_fight: 22 }],
    apl_sequence: [{ time_seconds: 1.25, id: 184367, name: "Rampage", internal_name: "rampage", target: "Fluffy Pillow", resources: { rage: 80 }, resource_max: { rage: 100 }, buffs: [{ id: 184362, name: "Enrage", internal_name: "enrage", stacks: 2 }] }],
  },
  generatedInput: prepared.generatedInput,
  rawJson: "{\"sim\":{}}",
  rawHtml: "<!doctype html><title>SimC</title>",
  stdout: "SimulationCraft",
  stderr: "",
  stdoutTruncated: false,
  stderrTruncated: false,
  artifactDirectory: "/tmp/artifacts",
} as const;

function leafKeys(value: object, prefix = ""): string[] {
  return Object.entries(value).flatMap(([key, nested]) => {
    const path = prefix ? `${prefix}.${key}` : key;
    return typeof nested === "object" && nested !== null ? leafKeys(nested, path) : [path];
  });
}

async function expectNoAutomatedAccessibilityViolations() {
  const result = await axe.run(document.body, {
    rules: { "color-contrast": { enabled: false } },
  });
  expect(result.violations).toEqual([]);
}

describe("application shell", () => {
  beforeEach(async () => {
    let currentTopGearSession = topGearSession("low_precision");
    let topGearStatusPolls = 0;
    mockInvoke.mockReset();
    mockOpen.mockReset();
    window.localStorage.clear();
    mockOpen.mockResolvedValue(null);
    iconStatus = emptyIconStatus;
    storagePaths = { ...defaultStoragePaths };
    storedProfiles = [];
    recoveredQuickJobs = [];
    recoveredTopGearSessions = [];
    runtimeStatusResult = missingRuntime;
    mockInvoke.mockImplementation((command: string, arguments_: unknown) => {
      if (command === "runtime_install_latest") return Promise.resolve(readyRuntime);
      if (command === "runtime_status") return Promise.resolve(runtimeStatusResult);
      if (command === "runtime_check_updates") return Promise.resolve(runtimeStatusResult);
      if (command === "icon_cache_status") return Promise.resolve(iconStatus);
      if (command === "icon_cache_clear") {
        iconStatus = emptyIconStatus;
        return Promise.resolve(iconStatus);
      }
      if (command === "storage_paths_get") return Promise.resolve(storagePaths);
      if (command === "storage_paths_save") {
        const request = (arguments_ as { request: Pick<typeof storagePaths, "workspace" | "simulationcraft" | "icons" | "exports"> }).request;
        storagePaths = { ...storagePaths, ...request };
        return Promise.resolve(storagePaths);
      }
      if (command === "storage_paths_reset") {
        storagePaths = { ...defaultStoragePaths };
        return Promise.resolve(storagePaths);
      }
      if (command === "window_state_reset") return Promise.resolve();
      if (command === "character_profiles") return Promise.resolve(storedProfiles);
      if (command === "character_profile_save_import") {
        const request = (arguments_ as { request: ReturnType<typeof import("./quick").defaultQuickRequest> }).request;
        const profile = {
          id: "a".repeat(32),
          identity: { region: "kr", realm: "azshara", characterName: "Core" },
          displayName: "Core",
          class: "warrior",
          specialization: "fury",
          favorite: false,
          inputSource: request.format,
          request,
          capturedAtUnixSeconds: 1_788_000_000,
          previousInputAvailable: false,
          armoryRefresh: { available: false, reason: "scheduled for 1.0" },
        } as const;
        storedProfiles = [profile];
        return Promise.resolve(profile);
      }
      if (command === "character_profile_set_favorite") {
        const request = arguments_ as { profileId: string; favorite: boolean };
        const profile = { ...storedProfiles.find(({ id }) => id === request.profileId)!, favorite: request.favorite };
        storedProfiles = [profile];
        return Promise.resolve(profile);
      }
      if (command === "character_profile_delete") {
        const request = arguments_ as { profileId: string };
        storedProfiles = storedProfiles.filter(({ id }) => id !== request.profileId);
        return Promise.resolve();
      }
      if (command === "character_profile_reload_armory") return Promise.reject(new Error("Armory reload is unavailable"));
      if (command === "character_profile_restore_previous") return Promise.resolve(storedProfiles[0]);
      if (command === "quick_recover") return Promise.resolve([]);
      if (command === "quick_jobs") return Promise.resolve(recoveredQuickJobs);
      if (command === "top_gear_sessions") return Promise.resolve(recoveredTopGearSessions);
      if (command === "top_gear_prepare") return Promise.resolve(topGearPrepared);
      if (command === "top_gear_start") {
        currentTopGearSession = topGearSession("low_precision");
        topGearStatusPolls = 0;
        return Promise.resolve(currentTopGearSession);
      }
      if (command === "top_gear_status") {
        topGearStatusPolls += 1;
        currentTopGearSession = topGearSession(topGearStatusPolls === 1 ? "medium_precision" : topGearStatusPolls === 2 ? "high_precision" : "complete");
        return Promise.resolve(currentTopGearSession);
      }
      if (command === "top_gear_result") return Promise.resolve(topGearResultFixture);
      if (command === "top_gear_export") return Promise.resolve({ directory: "/Documents/SimShredder Exports/top-gear-tg-test", fileCount: 5 });
      if (command === "top_gear_delete" || command === "quick_delete") return Promise.resolve();
      if (command === "top_gear_rerun") return Promise.resolve({ ...topGearSession("low_precision"), id: "tg-rerun" });
      if (command === "quick_prepare") return Promise.resolve(prepared);
      if (command === "quick_start" || command === "quick_job_status") return Promise.resolve(succeededJob);
      if (command === "quick_rerun") return Promise.resolve({ ...succeededJob, id: 70, state: "queued", succeededBatches: 0, pendingBatches: 1, attempts: [] });
      if (command === "quick_result") return Promise.resolve(quickResultFixture);
      if (command === "quick_export") return Promise.resolve({ directory: "/Documents/SimShredder Exports/quick-sim-7", fileCount: 5 });
      return Promise.reject(new Error("unexpected command: " + command));
    });
    await i18n.changeLanguage("en");
  });

  it("has complete, symmetric English and Korean catalogs", () => {
    expect(leafKeys(resources.ko.translation)).toEqual(leafKeys(resources.en.translation));
  });

  it("has no automated accessibility violations on primary entry screens", async () => {
    const user = userEvent.setup();
    render(<App />);

    await expectNoAutomatedAccessibilityViolations();
    await user.click(screen.getByRole("button", { name: "Profile" }));
    await expectNoAutomatedAccessibilityViolations();
    await user.click(screen.getByRole("button", { name: "Settings" }));
    await screen.findByText("1210-01 · 3487fce");
    await expectNoAutomatedAccessibilityViolations();
  });

  it("navigates by accessible controls without a pointer", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.tab();
    expect(screen.getByRole("link", { name: "Skip to content" })).toHaveFocus();
    await user.tab();
    expect(screen.getByRole("button", { name: "Home" })).toHaveFocus();
    await user.tab();
    const importNavigation = screen.getByRole("button", { name: "Profile" });
    expect(importNavigation).toHaveFocus();
    expect(importNavigation).toHaveAttribute("aria-label", "Profile");
    await user.keyboard("{Enter}");
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent(
      "Character profiles",
    );
    expect(screen.getByRole("button", { name: "Profile" })).toHaveAttribute("aria-current", "page");
  });

  it("switches locale without restarting", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.selectOptions(screen.getByRole("combobox", { name: "Language" }), "ko");
    expect(await screen.findByRole("button", { name: "프로필" })).toBeVisible();
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent(
      "WoW 장비 시뮬레이션",
    );
    expect(document.documentElement.lang).toBe("ko");
  });

  it("saves character inputs, favorites them, and disables unavailable Armory reload", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Profile" }));
    await user.type(screen.getByRole("textbox", { name: "Profile source" }), "warrior=Core");
    await user.click(screen.getByRole("button", { name: "Review profile" }));
    expect(await screen.findByRole("heading", { name: "Review simulation input" })).toBeVisible();
    expect(mockInvoke).toHaveBeenCalledWith("character_profile_save_import", {
      request: expect.objectContaining({ source: "warrior=Core", format: "simcFile", iterations: 10_000 }),
    });

    await user.click(screen.getByRole("button", { name: "Profile" }));
    expect(await screen.findByRole("heading", { name: "Saved characters" })).toBeVisible();
    const favorite = screen.getByRole("button", { name: "Add Core to favorites" });
    await user.click(favorite);
    expect(screen.getByRole("button", { name: "Remove Core from favorites" })).toHaveAttribute("aria-pressed", "true");

    const reloadArmory = screen.getByRole("button", { name: "Reload from Armory" });
    expect(reloadArmory).toBeDisabled();
    expect(reloadArmory).toHaveAttribute("title", expect.stringContaining("API broker will be enabled in 1.0"));
    await user.click(reloadArmory);
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
    expect(mockInvoke).not.toHaveBeenCalledWith("character_profile_reload_armory", expect.anything());
    await expectNoAutomatedAccessibilityViolations();

    await user.click(screen.getByRole("button", { name: "Use saved input" }));
    expect(await screen.findByRole("heading", { name: "Review simulation input" })).toBeVisible();
  });

  it("detects AddOn headers while treating headerless text as a regular simc profile", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Profile" }));
    const source = screen.getByRole("textbox", { name: "Profile source" });
    await user.type(source, "# Standard SimulationCraft profile\nrogue=Character");
    expect(screen.getByRole("radio", { name: ".simc file" })).toBeChecked();

    await user.clear(source);
    await user.type(source, "# SimC Addon 12.1.0-01\n# WoW 12.1.0.69497, TOC 120100\nrogue=Character");
    expect(screen.getByRole("radio", { name: "AddOn export" })).toBeChecked();
  });

  it("deletes a saved character profile only after confirmation", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Profile" }));
    await user.type(screen.getByRole("textbox", { name: "Profile source" }), "warrior=Core");
    await user.click(screen.getByRole("button", { name: "Review profile" }));
    await screen.findByRole("heading", { name: "Review simulation input" });
    await user.click(screen.getByRole("button", { name: "Profile" }));

    await user.click(await screen.findByRole("button", { name: "Delete profile" }));
    const dialog = screen.getByRole("dialog", { name: "Delete Core?" });
    expect(dialog).toHaveTextContent("Simulation history, results, and exported files are kept.");
    await expectNoAutomatedAccessibilityViolations();
    await user.click(within(dialog).getByRole("button", { name: "Delete profile" }));

    expect(mockInvoke).toHaveBeenCalledWith("character_profile_delete", { profileId: "a".repeat(32) });
    expect(await screen.findByText("No character profiles have been saved yet. Reviewing an input saves it here.")).toBeVisible();
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
  });

  it("shows core analysis controls and keeps deep SimC options collapsed", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Profile" }));
    await user.type(screen.getByRole("textbox", { name: "Profile source" }), "warrior=Core");
    await user.click(screen.getByRole("button", { name: "Review profile" }));
    expect(await screen.findByRole("heading", { name: "Simulation settings" })).toBeVisible();

    expect(screen.getByRole("radio", { name: "Fixed iterations" })).toBeChecked();
    expect(screen.getByLabelText(/Maximum fight length/)).toBeVisible();
    expect(screen.getByLabelText("Targets")).toBeVisible();
    expect(screen.getByLabelText("Fight style")).toBeVisible();
    expect(screen.getByRole("checkbox", { name: /Full raid buffs/ })).toBeChecked();
    expect(screen.getByRole("checkbox", { name: /Bloodlust/ })).toBeChecked();
    expect(screen.getByRole("checkbox", { name: /Profile consumables/ })).toBeChecked();
    expect(screen.getByLabelText("Target level")).not.toBeVisible();

    await user.click(screen.getByText("Advanced options"));
    expect(screen.getByLabelText("Target level")).toBeVisible();
    expect(screen.getByLabelText(/World latency/)).toBeVisible();
    expect(screen.getByLabelText(/Custom APL/)).toBeVisible();
    expect(screen.getByLabelText(/Custom SimC options/)).toBeVisible();

    await user.click(screen.getByRole("radio", { name: "Smart error target" }));
    expect(screen.getByLabelText(/Target error/)).toBeVisible();
    await user.selectOptions(screen.getByLabelText("Fight style"), "HeavyMovement");
    await user.clear(screen.getByLabelText(/Random seed/));
    await user.type(screen.getByLabelText(/Random seed/), "42");
    await user.click(screen.getByRole("button", { name: "Update preview" }));
    expect(mockInvoke).toHaveBeenLastCalledWith("quick_prepare", {
      request: expect.objectContaining({
        fightStyle: "HeavyMovement",
        analysis: expect.objectContaining({ precision: "smart", seed: 42 }),
      }),
    });
  });

  it("prepares the discovered runtime from the settings screen", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    expect(await screen.findByText("1210-01 · 3487fce")).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Download and install" }));
    expect(await screen.findByText("Ready")).toBeVisible();
    expect(mockInvoke).toHaveBeenCalledWith("runtime_install_latest");
  });

  it("keeps a healthy installed runtime ready when nightly discovery is unavailable", async () => {
    runtimeStatusResult = {
      ...readyRuntime,
      availableConfirmed: false,
      availableBuild: "removed1",
      diagnostic: "SIMSHREDDER_RUNTIME_NETWORK_UNAVAILABLE|HTTP 404",
    };
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    expect(await screen.findByText("Update status")).toBeVisible();
    expect(await screen.findByText("Using the installed version · latest status unavailable")).toBeVisible();
    expect(screen.getByText("Ready")).toBeVisible();
    expect(screen.queryByText("Update information is stale")).not.toBeInTheDocument();
    expect(screen.queryByText(/deadbee/)).not.toBeInTheDocument();
    expect(screen.queryByText("SimulationCraft could not be prepared")).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Install update" })).not.toBeInTheDocument();
  });

  it("shows a generic discovery notice when no runtime is installed", async () => {
    runtimeStatusResult = {
      ...missingRuntime,
      availableConfirmed: false,
      availableBuild: "removed1",
      diagnostic: "SIMSHREDDER_RUNTIME_NETWORK_UNAVAILABLE|HTTP 404",
    };
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    expect(await screen.findByText("Installation information is unavailable")).toBeVisible();
    expect(screen.getByText("Not currently available")).toBeVisible();
    expect(screen.getByText("SimulationCraft updates could not be checked because the network is unavailable. The installed build remains active.")).toBeVisible();
    expect(screen.queryByText(/deadbee/)).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Download and install" })).not.toBeInTheDocument();
  });

  it("localizes stable runtime network diagnostics without exposing backend details", () => {
    expect(formatRuntimeError("SIMSHREDDER_RUNTIME_NETWORK_UNAVAILABLE|connection refused", i18n.t))
      .toBe("SimulationCraft updates could not be checked because the network is unavailable. The installed build remains active.");
    expect(formatRuntimeError("SIMSHREDDER_RUNTIME_INSTALL_FAILED|raw Rust error", i18n.t))
      .toBe("SimulationCraft could not be installed or verified. The installed build remains active.");
  });

  it("shows the same installed runtime and game-data date on Home and Settings", async () => {
    runtimeStatusResult = readyRuntime;
    const user = userEvent.setup();
    render(<App />);

    expect(await screen.findByText("1210-01 · 3487fce · Game data Aug 25, 2026")).toBeVisible();
    expect(screen.getByText("Ready")).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Settings" }));
    expect(await screen.findByText("Aug 25, 2026")).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Home" }));
    expect(screen.getByText("Ready")).toBeVisible();
  });

  it("lets the user control completion notifications and sleep prevention", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    const notifications = screen.getByRole("checkbox", { name: /Completion notifications/ });
    const preventSleep = screen.getByRole("checkbox", { name: /Prevent system sleep/ });
    expect(notifications).not.toBeChecked();
    expect(preventSleep).toBeChecked();
    await user.click(notifications);
    expect(notifications).toBeChecked();
    expect(window.localStorage.getItem("simshredder.runNotifications")).toBe("true");
    await user.click(preventSleep);
    expect(preventSleep).not.toBeChecked();
    expect(window.localStorage.getItem("simshredder.preventSleepDuringRuns")).toBe("false");
  });

  it("keeps empty tool titles separate from their import guidance", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Character Analysis" }));
    expect(screen.getByRole("heading", { level: 1, name: "Review simulation input" })).toBeVisible();
    expect(screen.getByText("Import and review a profile before configuring the analysis.")).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Gear Optimizer" }));
    expect(screen.getByRole("heading", { level: 1, name: "Compare gear and upgrades" })).toBeVisible();
    expect(screen.getByText("Import a Retail Live profile before configuring Gear Optimizer.")).toBeVisible();
  });

  it("asks before updating SimulationCraft and accepts Later without installing", async () => {
    runtimeStatusResult = { ...readyRuntime, availableBuild: "02b39ce", updateAvailable: true };
    const user = userEvent.setup();
    render(<App />);

    const dialog = await screen.findByRole("dialog", { name: "A newer SimulationCraft build is available" });
    expect(dialog).toHaveTextContent("Installed build: 3487fce. Available build: 02b39ce.");
    expect(mockInvoke).not.toHaveBeenCalledWith("runtime_install_latest");
    await user.click(screen.getByRole("button", { name: "Later" }));
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
    expect(mockInvoke).not.toHaveBeenCalledWith("runtime_install_latest");
  });

  it("checks for a SimulationCraft update only once per local day", async () => {
    const first = render(<App />);
    await screen.findByRole("heading", { name: "WoW gear simulation" });
    await waitFor(() => {
      expect(mockInvoke.mock.calls.filter(([command]) => command === "runtime_status")).toHaveLength(1);
      expect(mockInvoke.mock.calls.filter(([command]) => command === "runtime_check_updates")).toHaveLength(1);
    });
    first.unmount();

    render(<App />);
    await screen.findByRole("heading", { name: "WoW gear simulation" });
    await waitFor(() => expect(mockInvoke.mock.calls.filter(([command]) => command === "runtime_status")).toHaveLength(2));
    expect(mockInvoke.mock.calls.filter(([command]) => command === "runtime_check_updates")).toHaveLength(1);
  });

  it("installs a detected SimulationCraft update only after Yes", async () => {
    runtimeStatusResult = { ...readyRuntime, availableBuild: "02b39ce", updateAvailable: true };
    const user = userEvent.setup();
    render(<App />);

    await screen.findByRole("dialog", { name: "A newer SimulationCraft build is available" });
    await user.click(screen.getByRole("button", { name: "Yes, update" }));
    expect(mockInvoke).toHaveBeenCalledWith("runtime_install_latest");
    expect(await screen.findByRole("heading", { name: "WoW gear simulation" })).toBeVisible();
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
  });

  it("clears the per-user icon cache from settings", async () => {
    iconStatus = { ...emptyIconStatus, usedBytes: 4096, iconCount: 1, mappingCount: 2 };
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    const clear = await screen.findByRole("button", { name: "Clear icon cache" });
    expect(clear).toBeEnabled();
    await user.click(clear);
    expect(mockInvoke).toHaveBeenCalledWith("icon_cache_clear");
    expect(await screen.findByText("0 MiB of 256 MiB · 0 images")).toBeVisible();
  });

  it("shows SimShredder defaults and saves independent storage locations", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    const workspace = await screen.findByRole("textbox", { name: /Simulation history and working files/ });
    expect(workspace).toHaveValue(defaultStoragePaths.workspace);
    expect(screen.queryByDisplayValue(/dev\.simshredder\.desktop/)).not.toBeInTheDocument();
    await user.clear(workspace);
    await user.type(workspace, "/Volumes/Fast/SimShredder Records");
    await user.click(screen.getByRole("button", { name: "Save locations" }));
    expect(mockInvoke).toHaveBeenCalledWith("storage_paths_save", {
      request: expect.objectContaining({ workspace: "/Volumes/Fast/SimShredder Records" }),
    });
    expect(await screen.findByText("Storage locations saved.")).toBeVisible();
  });

  it("selects a storage location with the native folder browser", async () => {
    mockOpen.mockResolvedValue("/Volumes/Fast/SimShredder History");
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    const browse = await screen.findByRole("button", { name: "Browse for Simulation history and working files folder" });
    await user.click(browse);

    expect(mockOpen).toHaveBeenCalledWith(expect.objectContaining({ directory: true, multiple: false }));
    expect(screen.getByRole("textbox", { name: /Simulation history and working files/ })).toHaveValue("/Volumes/Fast/SimShredder History");
  });

  it("resets the remembered window layout from settings", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    await user.click(await screen.findByRole("button", { name: "Reset window position and size" }));

    expect(mockInvoke).toHaveBeenCalledWith("window_state_reset");
    expect(await screen.findByText("The window was restored to its default size and centered.")).toBeVisible();
  });

  it("completes import, preview, persistent job, result, and raw artifact flow", async () => {
    const user = userEvent.setup();
    render(<App />);
    await user.click(screen.getByRole("button", { name: "Profile" }));
    await user.type(screen.getByRole("textbox", { name: "Profile source" }), "warrior=Core");
    await user.click(screen.getByRole("button", { name: "Review profile" }));
    expect(await screen.findByRole("heading", { name: "Review simulation input" })).toBeVisible();
    expect(screen.getByText("Core")).toBeVisible();
    await user.click(screen.getByText("Input compatibility"));
    expect(screen.getByText("Preserved, not editable: 1")).toBeVisible();
    const compatibilityLine = screen.getByText(/Line 7 · raid_events/);
    expect(compatibilityLine).toBeVisible();
    expect(compatibilityLine.closest("li")).toHaveTextContent("Preserved exactly and delegated to SimulationCraft");
    const talentDetails = screen.getByRole("button", { name: "Show details for Talent configuration" });
    expect(talentDetails).toBeVisible();
    await user.click(talentDetails);
    expect(screen.getByRole("dialog")).toHaveTextContent("Talent loadoutCgEAAAAAAAA");
    expect(screen.queryByRole("button", { name: "View on Wowhead" })).not.toBeInTheDocument();
    await user.keyboard("{Escape}");
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
    expect(talentDetails).toHaveFocus();
    await user.click(screen.getByRole("button", { name: "Start analysis" }));
    expect(await screen.findByText("123,456.7")).toBeVisible();
    expect(screen.getByRole("button", { name: /Core · fury/ })).toHaveTextContent("Succeeded");
    await expectNoAutomatedAccessibilityViolations();
    expect(screen.getByRole("heading", { name: "Damage and healing breakdown" })).toBeVisible();
    expect(screen.getByRole("heading", { name: "Resources" })).toBeVisible();
    expect(screen.getByRole("heading", { name: "Buffs" })).toBeVisible();
    expect(screen.getByRole("heading", { name: "Sample action sequence" })).toBeVisible();
    expect(screen.getByRole("columnheader", { name: "Active buffs" })).toBeVisible();
    expect(screen.getByLabelText("2 stacks")).toBeVisible();
    expect(screen.getAllByRole("button", { name: "Show details for Rampage" })).toHaveLength(2);
    expect(screen.getAllByRole("button", { name: "Show details for Enrage" })).toHaveLength(2);
    await expectNoAutomatedAccessibilityViolations();
    await user.click(screen.getByRole("tab", { name: "Raw HTML" }));
    expect(screen.getByText(/HTML is shown as source text/)).toBeVisible();
    expect(screen.getByText("<!doctype html><title>SimC</title>")).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Export verified artifacts" }));
    expect(await screen.findByText(/Exported 5 files/)).toBeVisible();
    expect(mockInvoke).toHaveBeenCalledWith("quick_start", expect.objectContaining({ request: expect.objectContaining({ source: "warrior=Core" }) }));
  });

  it("previews the bilingual gear optimizer with virtual augmentation controls", async () => {
    const user = userEvent.setup();
    render(<App />);
    await user.click(screen.getByRole("button", { name: "Profile" }));
    await user.type(screen.getByRole("textbox", { name: "Profile source" }), "warrior=Core");
    await user.click(screen.getByRole("button", { name: "Review profile" }));
    await user.click(screen.getByRole("button", { name: "Gear Optimizer" }));
    expect(await screen.findByRole("heading", { name: "Compare gear and upgrades" })).toBeVisible();
    expect(await screen.findByText("Exact execution preview")).toBeVisible();
    expect(screen.getByRole("button", { name: "Add virtual variant" })).toBeEnabled();
    expect(screen.getByRole("heading", { name: "Gear candidates" })).toBeVisible();
    expect(screen.getByRole("heading", { name: "Omnium Folio" })).toBeVisible();
    expect(screen.getAllByRole("button", { name: /Show details for .*Helm/ }).length).toBeGreaterThan(0);
    expect(screen.getByRole("checkbox", { name: /Candidate Helm/ })).toBeChecked();
    expect(screen.getAllByText("Equipped", { selector: ".candidate-origin-badge" }).length).toBeGreaterThan(0);
    expect(screen.getAllByText("Bag", { selector: ".candidate-origin-badge" }).length).toBeGreaterThan(0);
    expect(screen.getByText("Manual", { selector: ".candidate-origin-badge" })).toBeVisible();
    expect(screen.getAllByText("Selected", { selector: ".candidate-state-badge" }).length).toBeGreaterThan(0);
    expect(screen.getByText(/Item ID 154030/)).toBeVisible();
    expect(screen.getAllByText("Gems: None · Enchant: None").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Current only (upgrade data unavailable)").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Catalyst: No confirmed use").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Trinkets · choose 2")).toHaveLength(2);
    expect(screen.queryByText("Trinket 1")).not.toBeInTheDocument();
    expect(screen.queryByText("Trinket 2")).not.toBeInTheDocument();
    expect(screen.getByRole("checkbox", { name: /Dungeon/ })).not.toBeChecked();
    await user.type(screen.getByRole("textbox", { name: "Encoded Omnium talents" }), "123:1/456:2");
    await user.click(screen.getByRole("button", { name: "Add Folio candidate" }));
    expect(mockInvoke).toHaveBeenCalledWith("top_gear_prepare", expect.objectContaining({ request: expect.objectContaining({ profileOptions: expect.objectContaining({ omnium_talents: expect.arrayContaining([expect.objectContaining({ value: "123:1/456:2", enabled: true })]) }) }) }));
    const upgradePolicy = screen.getByRole("combobox", { name: "How should item upgrades be compared?" });
    expect(upgradePolicy).toHaveValue("max_potential");
    expect(screen.getByText(/Open an item upgrade vendor in WoW, run \/simc debug/)).toBeVisible();
    expect(screen.getByText(/Runs automatically at 1%, 0.2%, then 0.05% target error/)).toBeVisible();
    expect(screen.getByText("Low precision")).toBeVisible();
    expect(screen.getByText("Medium precision (maximum)")).toBeVisible();
    expect(screen.getByText("High precision (maximum)")).toBeVisible();
    expect(screen.getByRole("heading", { name: "Reduce the workload" })).toBeVisible();
    expect(screen.queryByRole("heading", { name: "Confirmed currency budget" })).not.toBeInTheDocument();
    await user.selectOptions(upgradePolicy, "budget_constrained");
    expect(await screen.findByRole("heading", { name: "Confirmed currency budget" })).toBeVisible();
    expect(mockInvoke).toHaveBeenCalledWith("top_gear_prepare", expect.objectContaining({ request: expect.objectContaining({ enhancementPolicy: "budget_constrained" }) }));
    expect(screen.getByText(/No upgrade candidates with confirmed costs/)).toBeVisible();
    expect(screen.getByText(/No confirmed catalyst variants/)).toBeVisible();
    const championActions = screen.getByRole("group", { name: "Champion Mistcrest quick balance actions" });
    const championRow = championActions.closest(".currency-row") as HTMLElement;
    const championBalance = within(championRow).getByRole("spinbutton", { name: "Current balance" });
    await user.click(within(championActions).getByRole("button", { name: "+10" }));
    expect(championBalance).toHaveValue(10);
    await user.click(within(championActions).getByRole("button", { name: "+100" }));
    expect(championBalance).toHaveValue(110);
    await user.click(within(championActions).getByRole("button", { name: "Max" }));
    expect(championBalance).toHaveValue(99_999);
    const catalystInput = screen.getByRole("spinbutton", { name: "Available catalyst charges" });
    await user.click(within(screen.getByRole("group", { name: "Catalyst charge quick actions" })).getByRole("button", { name: "+1" }));
    expect(catalystInput).toHaveValue(1);
    await user.click(screen.getByRole("button", { name: "Max all currencies" }));
    for (const balance of screen.getAllByRole("spinbutton", { name: "Current balance" })) expect(balance).toHaveValue(99_999);
    expect(catalystInput).toHaveValue(1);
    await user.click(screen.getByRole("button", { name: "Lock Head" }));
    expect(
      screen.getAllByText("Excluded: slot locked", { selector: ".candidate-exclusion" }),
    ).toHaveLength(2);
    expect(mockInvoke).toHaveBeenCalledWith("top_gear_prepare", expect.objectContaining({ request: expect.objectContaining({ lockedSlots: ["head"] }) }));
    await user.click(screen.getByRole("button", { name: "Lock Trinkets · choose 2" }));
    expect(mockInvoke).toHaveBeenCalledWith("top_gear_prepare", expect.objectContaining({ request: expect.objectContaining({ lockedSlots: ["head", "trinket1", "trinket2"] }) }));
    await user.click(screen.getByRole("checkbox", { name: /Dungeon/ }));
    expect(mockInvoke).toHaveBeenCalledWith("top_gear_prepare", expect.objectContaining({ request: expect.objectContaining({ talentLoadouts: expect.arrayContaining([expect.objectContaining({ key: "saved-0", enabled: true })]) }) }));
    await expectNoAutomatedAccessibilityViolations();
  });

  it("keeps adaptive gear-optimizer stages explicit and exports the verified result", async () => {
    const user = userEvent.setup();
    render(<App />);
    await user.click(screen.getByRole("button", { name: "Profile" }));
    await user.type(screen.getByRole("textbox", { name: "Profile source" }), "warrior=Core");
    await user.click(screen.getByRole("button", { name: "Review profile" }));
    await user.click(screen.getByRole("button", { name: "Gear Optimizer" }));
    await screen.findByText("Exact execution preview");
    await user.click(screen.getByRole("button", { name: "Start Gear Optimizer" }));
    expect(await screen.findByRole("heading", { name: "Job status" })).toBeVisible();
    expect(await screen.findByRole("heading", { name: "Broad low-precision search" })).toBeVisible();
    expect(screen.queryByRole("button", { name: "Continue to the next verified stage" })).not.toBeInTheDocument();
    expect(screen.getByRole("list", { name: "Gear optimization stages" })).toHaveTextContent("Medium-precision survivor search");
    expect(await screen.findByText("Verified loadout ranking", {}, { timeout: 2_500 })).toBeVisible();
    expect(screen.getByText("The top result improves on your equipped setup")).toBeVisible();
    expect(screen.getByText("+500 vs. equipped")).toBeVisible();
    expect(screen.getByText("+0.4% vs. equipped")).toBeVisible();
    expect(screen.getByRole("heading", { name: "Recommended changes" })).toBeVisible();
    expect(screen.getByText("Equip Candidate Helm")).toBeVisible();
    expect(screen.getAllByText("Crests", { selector: ".currency-name" }).length).toBeGreaterThan(0);
    expect(screen.getByRole("button", { name: "Copy final .simc input" })).toBeVisible();
    expect(screen.getByRole("button", { name: "Run again with the same input and settings" })).toBeVisible();
    expect(screen.getByText("+500")).toBeVisible();
    expect(screen.getByRole("combobox", { name: "Result filter" })).toBeVisible();
    expect(screen.getByRole("combobox", { name: "Sort by" })).toBeVisible();
    expect(screen.getByText("Candidate Helm")).toBeVisible();
    expect(screen.getAllByText("Changed from equipped").length).toBeGreaterThan(0);
    expect(screen.getByText("Candidate Helm").closest("li")).toHaveClass("loadout-item-changed");
    expect(screen.getByRole("button", { name: "Use rank 1 as the comparison reference" })).toBeVisible();
    expect(screen.getByText("+0.4%")).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Use rank 1 as the comparison reference" }));
    expect(screen.getByRole("heading", { name: "Rank 1 loadout" })).toBeVisible();
    expect(screen.getByText("-500")).toBeVisible();
    await expectNoAutomatedAccessibilityViolations();
    await user.click(screen.getByRole("button", { name: "Export verified Gear Optimizer artifacts" }));
    expect(await screen.findByText(/Exported 5 files/)).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Run again with the same input and settings" }));
    expect(mockInvoke).toHaveBeenCalledWith("top_gear_rerun", { sessionId: "tg-test" });
  });

  it("uses History as the saved run archive and switches between completed results", async () => {
    recoveredTopGearSessions = [
      topGearSession("complete"),
      { ...topGearSession("complete"), id: "tg-older", lowJobId: 11, highJobId: 12, currentJob: { ...succeededJob, id: 12 } },
    ];
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "History" }));
    expect(await screen.findByRole("heading", { name: "Run history" })).toBeVisible();
    expect(screen.getByText(/Session tg-test/)).toBeVisible();
    expect(screen.getByText(/Session tg-older/)).toBeVisible();
    const historyEntries = screen.getAllByRole("listitem");
    await user.click(within(historyEntries.find((entry) => entry.textContent?.includes("tg-older"))!).getByRole("button", { name: "Open result" }));

    const chooser = await screen.findByRole("list", { name: "Completed results" });
    expect(within(chooser).getAllByRole("button")).toHaveLength(2);
    expect(mockInvoke).toHaveBeenCalledWith("top_gear_result", { sessionId: "tg-older" });
    await user.click(within(chooser).getAllByRole("button")[0]);
    expect(await screen.findByRole("heading", { name: "Gear Optimizer result" })).toBeVisible();
    expect(mockInvoke).toHaveBeenCalledWith("top_gear_result", { sessionId: "tg-test" });
  });

  it("deletes a terminal run from local History only after confirmation", async () => {
    recoveredTopGearSessions = [topGearSession("complete")];
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "History" }));
    expect(await screen.findByText(/Session tg-test/)).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Delete Gear Optimizer Session tg-test" }));
    expect(screen.getByRole("dialog")).toHaveTextContent("The run record and artifacts used only by this run will be permanently deleted");
    await user.click(within(screen.getByRole("dialog")).getByRole("button", { name: "Delete run" }));

    await waitFor(() => expect(screen.queryByText(/Session tg-test/)).not.toBeInTheDocument());
    expect(mockInvoke).toHaveBeenCalledWith("top_gear_delete", { sessionId: "tg-test" });
  });

  it("filters terminal history and starts an exact rerun as a new persistent identity", async () => {
    recoveredQuickJobs = [succeededJob, { ...succeededJob, id: 8, state: "failed", profile: { ...succeededJob.profile, name: "Other" } }];
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "History" }));
    await user.type(screen.getByRole("textbox", { name: /Search/ }), "Core");
    expect(screen.getByText(/Job #7/)).toBeVisible();
    expect(screen.queryByText(/Job #8/)).not.toBeInTheDocument();
    await user.click(screen.getByRole("button", { name: "Run again" }));

    expect(mockInvoke).toHaveBeenCalledWith("quick_rerun", { jobId: 7 });
    expect(await screen.findByRole("heading", { name: "Job status" })).toBeVisible();
    expect(screen.getByText("Job #70")).toBeVisible();
  });
});
