import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import axe from "axe-core";
import { beforeEach, describe, expect, it, vi } from "vitest";
import i18n, { resources } from "./i18n";
import { App } from "./App";

const { mockInvoke, mockOpen } = vi.hoisted(() => ({ mockInvoke: vi.fn(), mockOpen: vi.fn() }));

vi.mock("@tauri-apps/api/core", () => ({ invoke: mockInvoke }));
vi.mock("@tauri-apps/plugin-dialog", () => ({ open: mockOpen }));
vi.mock("echarts/core", () => ({
  use: vi.fn(),
  init: () => ({ setOption: vi.fn(), resize: vi.fn(), dispose: vi.fn() }),
}));
vi.mock("echarts/charts", () => ({ BarChart: {} }));
vi.mock("echarts/components", () => ({ GridComponent: {}, TooltipComponent: {} }));
vi.mock("echarts/renderers", () => ({ CanvasRenderer: {} }));

const missingRuntime = {
  state: "missing",
  active: null,
  installed: [],
  availableVersion: "1210-01",
  availableBuild: "3487fce",
  updateAvailable: false,
  diagnostic: null,
} as const;

const readyRuntime = {
  ...missingRuntime,
  state: "ready",
  active: {
    id: "1210-01-3487fce",
    simcVersion: "1210-01",
    build: "3487fce",
    gameVersion: "12.1.0.69465",
    channel: "live",
    executableSha256: "a".repeat(64),
    installedAtUnixSeconds: 1,
  },
  installed: [],
} as const;

let runtimeStatusResult: unknown = missingRuntime;

const emptyIconStatus = { budgetBytes: 268435456, usedBytes: 0, iconCount: 0, mappingCount: 0, remoteProviderEnabled: false } as const;
let iconStatus: { budgetBytes: number; usedBytes: number; iconCount: number; mappingCount: number; remoteProviderEnabled: boolean } = emptyIconStatus;

const defaultStoragePaths = {
  configRoot: "/Users/test/Library/Application Support/SimShredder",
  workspace: "/Users/test/Library/Application Support/SimShredder/workspace",
  simulationcraft: "/Users/test/Library/Application Support/SimShredder/simulationcraft",
  icons: "/Users/test/Library/Application Support/SimShredder/icons",
  exports: "/Users/test/Documents/SimShredder Exports",
  defaultWorkspace: "/Users/test/Library/Application Support/SimShredder/workspace",
  defaultSimulationcraft: "/Users/test/Library/Application Support/SimShredder/simulationcraft",
  defaultIcons: "/Users/test/Library/Application Support/SimShredder/icons",
  defaultExports: "/Users/test/Documents/SimShredder Exports",
} as const;
let storagePaths = { ...defaultStoragePaths };

const prepared = {
  profile: { name: "Core", class: "warrior", specialization: "fury", race: "orc", role: "attack", level: 90, equippedItems: 0, bagItems: 0, talents: [{ name: "talents", value: "CgEAAAAAAAA" }], warnings: [] },
  generatedInput: "# Generated by SimShredder\nwarrior=Core\niterations=10000\n",
  threads: 4,
  profilesetWorkThreads: 2,
} as const;

const succeededJob = {
  id: 7,
  state: "succeeded",
  cancelRequested: false,
  failure: null,
  succeededBatches: 1,
  pendingBatches: 0,
  attempts: [{ id: 8, sequence: 1, state: "succeeded", failure: null, cacheHit: false, stdoutLogTruncated: false, stderrLogTruncated: false }],
} as const;

const topGearPrepared = {
  profileName: "Core",
  ruleRevision: "12.1.0-69465-v1",
  ruleSource: "Manual input contract",
  rawCombinations: 2,
  validCombinations: 2,
  executionCount: 4,
  finalistCount: 2,
  estimated: false,
  rejections: { dominatedVariants: 0, socketLimit: 0, enchantSlot: 0, uniqueEquipped: 0, embellishmentLimit: 0, weaponConstraint: 0, budget: 0, symmetricDuplicate: 0 },
  generatedInput: "warrior=Core\nprofileset.0123abcd=default_actions=1\n",
  variants: [{ key: "worn-head-154029", sourceItemId: 154029, slot: "head", rank: 0, gemIds: [], enchantId: null, simcOptions: {}, cost: {}, actions: [], uniqueGroups: [], weaponKind: "none", embellishment: false, changed: false }],
  loadouts: [],
} as const;

const topGearSession = (stage: "low_precision" | "high_precision" | "complete") => ({
  id: "tg-test",
  stage,
  currentJob: succeededJob,
  lowJobId: 7,
  highJobId: stage === "low_precision" ? null : 9,
  actionJobId: null,
  completedExecutions: stage === "low_precision" ? 2 : 4,
  totalExecutions: 4,
  canAdvance: stage !== "complete",
});

const topGearResultFixture = {
  sessionId: "tg-test",
  baselineKey: "baseline",
  ruleRevision: "12.1.0-69465-v1",
  ranked: [{ loadout: { key: "winner", items: {}, cost: { crest: 5 }, changedSlots: 1 }, mean: 123500, meanError: 50, delta: 500, combinedError: 70, equivalentToBaseline: false, paretoOptimal: true, rank: 1 }],
  lowJobId: 7,
  highJobId: 9,
  actionJobId: null,
  actionPlan: [],
  estimated: false,
  finalGeneratedInput: "warrior=Core\nprofileset.winner=head=,id=154029\n",
  runtime: { simc_version: "1210-01", git_revision: "3487fce", game_version: "12.1.0.69465", game_build: 69465, channel: "live" },
  budget: { balances: { crest: 10 }, reserves: { crest: 2 }, confirmedAtUnixSeconds: 1 },
} as const;

const quickResultFixture = {
  jobId: 7,
  result: {
    schema_version: 2,
    report_version: "2.0.0",
    runtime: { simc_version: "1210-01", git_revision: "3487fce", game_version: "12.1.0.69465", game_build: 69465, channel: "live" },
    player: { name: "Core", race: "Orc", role: "attack", specialization: "Fury" },
    options: { iterations: 10000, threads: 4, seed: 1, max_time_seconds: 300, desired_targets: 1, fight_style: "Patchwerk" },
    primary_metric: { name: "DPS", mean: 123456.7, mean_error: 120.2, standard_deviation: 500, minimum: 120000, maximum: 126000, median: 123400 },
    actions: [{ id: 184367, name: "Rampage", internal_name: "rampage", school: "physical", executes: 24.5, amount_per_fight: 1234567, metric_per_second: 45678.9, share: 0.37 }],
    buffs: [{ id: 184362, name: "Enrage", internal_name: "enrage", uptime_percent: 82.4, benefit_percent: 91.2, starts: 18 }],
    resources: [{ name: "rage", spent_per_fight: 1200, overflow_per_fight: 18, remaining_per_fight: 22 }],
    apl_sequence: [{ time_seconds: 1.25, id: 184367, name: "Rampage", internal_name: "rampage", target: "Fluffy Pillow", resources: { rage: 80 }, resource_max: { rage: 100 } }],
  },
  generatedInput: prepared.generatedInput,
  rawJson: "{\"sim\":{}}",
  rawHtml: "<!doctype html><title>SimC</title>",
  stdout: "SimulationCraft",
  stderr: "",
  stdoutTruncated: false,
  stderrTruncated: false,
  artifactDirectory: "/tmp/artifacts",
} as const;

function leafKeys(value: object, prefix = ""): string[] {
  return Object.entries(value).flatMap(([key, nested]) => {
    const path = prefix ? `${prefix}.${key}` : key;
    return typeof nested === "object" && nested !== null ? leafKeys(nested, path) : [path];
  });
}

async function expectNoAutomatedAccessibilityViolations() {
  const result = await axe.run(document.body, {
    rules: { "color-contrast": { enabled: false } },
  });
  expect(result.violations).toEqual([]);
}

describe("application shell", () => {
  beforeEach(async () => {
    let currentTopGearSession = topGearSession("low_precision");
    let topGearAdvances = 0;
    mockInvoke.mockReset();
    mockOpen.mockReset();
    window.localStorage.clear();
    mockOpen.mockResolvedValue(null);
    iconStatus = emptyIconStatus;
    storagePaths = { ...defaultStoragePaths };
    runtimeStatusResult = missingRuntime;
    mockInvoke.mockImplementation((command: string, arguments_: unknown) => {
      if (command === "runtime_install_latest") return Promise.resolve(readyRuntime);
      if (command === "runtime_status") return Promise.resolve(runtimeStatusResult);
      if (command === "icon_cache_status") return Promise.resolve(iconStatus);
      if (command === "icon_cache_clear") {
        iconStatus = emptyIconStatus;
        return Promise.resolve(iconStatus);
      }
      if (command === "storage_paths_get") return Promise.resolve(storagePaths);
      if (command === "storage_paths_save") {
        const request = (arguments_ as { request: Pick<typeof storagePaths, "workspace" | "simulationcraft" | "icons" | "exports"> }).request;
        storagePaths = { ...storagePaths, ...request };
        return Promise.resolve(storagePaths);
      }
      if (command === "storage_paths_reset") {
        storagePaths = { ...defaultStoragePaths };
        return Promise.resolve(storagePaths);
      }
      if (command === "quick_recover") return Promise.resolve([]);
      if (command === "top_gear_sessions") return Promise.resolve([]);
      if (command === "top_gear_prepare") return Promise.resolve(topGearPrepared);
      if (command === "top_gear_start") {
        currentTopGearSession = topGearSession("low_precision");
        topGearAdvances = 0;
        return Promise.resolve(currentTopGearSession);
      }
      if (command === "top_gear_status") return Promise.resolve(currentTopGearSession);
      if (command === "top_gear_advance") {
        topGearAdvances += 1;
        currentTopGearSession = topGearSession(topGearAdvances === 1 ? "high_precision" : "complete");
        return Promise.resolve(currentTopGearSession);
      }
      if (command === "top_gear_result") return Promise.resolve(topGearResultFixture);
      if (command === "top_gear_export") return Promise.resolve({ directory: "/Documents/SimShredder Exports/top-gear-tg-test", fileCount: 5 });
      if (command === "quick_prepare") return Promise.resolve(prepared);
      if (command === "quick_start" || command === "quick_job_status") return Promise.resolve(succeededJob);
      if (command === "quick_result") return Promise.resolve(quickResultFixture);
      if (command === "quick_export") return Promise.resolve({ directory: "/Documents/SimShredder Exports/quick-sim-7", fileCount: 5 });
      return Promise.reject(new Error("unexpected command: " + command));
    });
    await i18n.changeLanguage("en");
  });

  it("has complete, symmetric English and Korean catalogs", () => {
    expect(leafKeys(resources.ko.translation)).toEqual(leafKeys(resources.en.translation));
  });

  it("has no automated accessibility violations on primary entry screens", async () => {
    const user = userEvent.setup();
    render(<App />);

    await expectNoAutomatedAccessibilityViolations();
    await user.click(screen.getByRole("button", { name: "Import" }));
    await expectNoAutomatedAccessibilityViolations();
    await user.click(screen.getByRole("button", { name: "Settings" }));
    await screen.findByText("1210-01 · 3487fce");
    await expectNoAutomatedAccessibilityViolations();
  });

  it("navigates by accessible controls without a pointer", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.tab();
    expect(screen.getByRole("link", { name: "Skip to content" })).toHaveFocus();
    await user.tab();
    expect(screen.getByRole("button", { name: "Home" })).toHaveFocus();
    await user.tab();
    const importNavigation = screen.getByRole("button", { name: "Import" });
    expect(importNavigation).toHaveFocus();
    expect(importNavigation).toHaveAttribute("aria-label", "Import");
    await user.keyboard("{Enter}");
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent(
      "Bring your character into focus.",
    );
    expect(screen.getByRole("button", { name: "Import" })).toHaveAttribute("aria-current", "page");
  });

  it("switches locale without restarting", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.selectOptions(screen.getByRole("combobox", { name: "Language" }), "ko");
    expect(await screen.findByRole("button", { name: "가져오기" })).toBeVisible();
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent(
      "WoW 장비를 시뮬레이션하고 비교하세요.",
    );
    expect(document.documentElement.lang).toBe("ko");
  });

  it("prepares the pinned runtime from the settings screen", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    expect(await screen.findByText("1210-01 · 3487fce")).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Download and install" }));
    expect(await screen.findByText("Ready")).toBeVisible();
    expect(mockInvoke).toHaveBeenCalledWith("runtime_install_latest");
  });

  it("asks before updating SimulationCraft and accepts Later without installing", async () => {
    runtimeStatusResult = { ...readyRuntime, availableBuild: "02b39ce", updateAvailable: true };
    const user = userEvent.setup();
    render(<App />);

    const dialog = await screen.findByRole("dialog", { name: "A newer SimulationCraft build is available" });
    expect(dialog).toHaveTextContent("Installed build: 3487fce. Available build: 02b39ce.");
    expect(mockInvoke).not.toHaveBeenCalledWith("runtime_install_latest");
    await user.click(screen.getByRole("button", { name: "Later" }));
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
    expect(mockInvoke).not.toHaveBeenCalledWith("runtime_install_latest");
  });

  it("checks for a SimulationCraft update only once per local day", async () => {
    const first = render(<App />);
    await screen.findByRole("heading", { name: "Simulate and compare your WoW gear." });
    expect(mockInvoke.mock.calls.filter(([command]) => command === "runtime_status")).toHaveLength(1);
    first.unmount();

    render(<App />);
    await screen.findByRole("heading", { name: "Simulate and compare your WoW gear." });
    expect(mockInvoke.mock.calls.filter(([command]) => command === "runtime_status")).toHaveLength(1);
  });

  it("installs a detected SimulationCraft update only after Yes", async () => {
    runtimeStatusResult = { ...readyRuntime, availableBuild: "02b39ce", updateAvailable: true };
    const user = userEvent.setup();
    render(<App />);

    await screen.findByRole("dialog", { name: "A newer SimulationCraft build is available" });
    await user.click(screen.getByRole("button", { name: "Yes, update" }));
    expect(mockInvoke).toHaveBeenCalledWith("runtime_install_latest");
    expect(await screen.findByRole("heading", { name: "Simulate and compare your WoW gear." })).toBeVisible();
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
  });

  it("clears the per-user icon cache from settings", async () => {
    iconStatus = { ...emptyIconStatus, usedBytes: 4096, iconCount: 1, mappingCount: 2 };
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    const clear = await screen.findByRole("button", { name: "Clear icon cache" });
    expect(clear).toBeEnabled();
    await user.click(clear);
    expect(mockInvoke).toHaveBeenCalledWith("icon_cache_clear");
    expect(await screen.findByText("0 MiB of 256 MiB · 0 images")).toBeVisible();
  });

  it("shows SimShredder defaults and saves independent storage locations", async () => {
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    const workspace = await screen.findByRole("textbox", { name: /Simulation history and working files/ });
    expect(workspace).toHaveValue(defaultStoragePaths.workspace);
    expect(screen.queryByDisplayValue(/dev\.simshredder\.desktop/)).not.toBeInTheDocument();
    await user.clear(workspace);
    await user.type(workspace, "/Volumes/Fast/SimShredder Records");
    await user.click(screen.getByRole("button", { name: "Save locations" }));
    expect(mockInvoke).toHaveBeenCalledWith("storage_paths_save", {
      request: expect.objectContaining({ workspace: "/Volumes/Fast/SimShredder Records" }),
    });
    expect(await screen.findByText("Storage locations saved.")).toBeVisible();
  });

  it("selects a storage location with the native folder browser", async () => {
    mockOpen.mockResolvedValue("/Volumes/Fast/SimShredder History");
    const user = userEvent.setup();
    render(<App />);

    await user.click(screen.getByRole("button", { name: "Settings" }));
    const browse = await screen.findByRole("button", { name: "Browse for Simulation history and working files folder" });
    await user.click(browse);

    expect(mockOpen).toHaveBeenCalledWith(expect.objectContaining({ directory: true, multiple: false }));
    expect(screen.getByRole("textbox", { name: /Simulation history and working files/ })).toHaveValue("/Volumes/Fast/SimShredder History");
  });

  it("completes import, preview, persistent job, result, and raw artifact flow", async () => {
    const user = userEvent.setup();
    render(<App />);
    await user.click(screen.getByRole("button", { name: "Import" }));
    await user.type(screen.getByRole("textbox", { name: "Profile source" }), "warrior=Core");
    await user.click(screen.getByRole("button", { name: "Review profile" }));
    expect(await screen.findByRole("heading", { name: "Review every input before the run." })).toBeVisible();
    expect(screen.getByText("Core")).toBeVisible();
    expect(screen.getByRole("button", { name: "Show details for Talent configuration" })).toBeVisible();
    expect(screen.getByRole("tooltip")).toHaveTextContent("Talent loadoutCgEAAAAAAAA");
    expect(screen.queryByRole("button", { name: "View on Wowhead" })).not.toBeInTheDocument();
    await user.click(screen.getByRole("button", { name: "Start Quick Sim" }));
    expect((await screen.findAllByText("Succeeded"))[0]).toBeVisible();
    expect(screen.getByRole("progressbar")).toHaveAccessibleName("1 of 1 batches complete");
    await expectNoAutomatedAccessibilityViolations();
    await user.click(screen.getByRole("button", { name: "View result" }));
    expect(await screen.findByText("123,456.7")).toBeVisible();
    expect(screen.getByRole("heading", { name: "Damage and healing breakdown" })).toBeVisible();
    expect(screen.getByRole("heading", { name: "Resources" })).toBeVisible();
    expect(screen.getByRole("heading", { name: "Buffs" })).toBeVisible();
    expect(screen.getByRole("heading", { name: "Sample action sequence" })).toBeVisible();
    expect(screen.getAllByRole("button", { name: "Show details for Rampage" })).toHaveLength(2);
    expect(screen.getByRole("button", { name: "Show details for Enrage" })).toBeVisible();
    await expectNoAutomatedAccessibilityViolations();
    await user.click(screen.getByRole("tab", { name: "Raw HTML" }));
    expect(screen.getByText(/HTML is shown as source text/)).toBeVisible();
    expect(screen.getByText("<!doctype html><title>SimC</title>")).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Export verified artifacts" }));
    expect(await screen.findByText(/Exported 5 files/)).toBeVisible();
    expect(mockInvoke).toHaveBeenCalledWith("quick_start", expect.objectContaining({ request: expect.objectContaining({ source: "warrior=Core" }) }));
  });

  it("previews a bilingual Top Gear search with virtual augmentation controls", async () => {
    const user = userEvent.setup();
    render(<App />);
    await user.click(screen.getByRole("button", { name: "Import" }));
    await user.type(screen.getByRole("textbox", { name: "Profile source" }), "warrior=Core");
    await user.click(screen.getByRole("button", { name: "Review profile" }));
    await user.click(screen.getByRole("button", { name: "Top Gear" }));
    expect(await screen.findByRole("heading", { name: "Spend every upgrade with evidence." })).toBeVisible();
    expect(await screen.findByText("Exact execution preview")).toBeVisible();
    expect(screen.getByRole("button", { name: "Add virtual variant" })).toBeEnabled();
    await expectNoAutomatedAccessibilityViolations();
  });

  it("keeps adaptive Top Gear stages explicit and exports the verified result", async () => {
    const user = userEvent.setup();
    render(<App />);
    await user.click(screen.getByRole("button", { name: "Import" }));
    await user.type(screen.getByRole("textbox", { name: "Profile source" }), "warrior=Core");
    await user.click(screen.getByRole("button", { name: "Review profile" }));
    await user.click(screen.getByRole("button", { name: "Top Gear" }));
    await screen.findByText("Exact execution preview");
    await user.click(screen.getByRole("button", { name: "Start Top Gear" }));
    expect(await screen.findByText("Broad low-precision search")).toBeVisible();
    expect(screen.getByRole("progressbar")).toHaveAccessibleName("2 of 4 planned profiles evaluated");
    await user.click(screen.getByRole("button", { name: "Continue to the next verified stage" }));
    expect(await screen.findByText("High-precision finalist verification")).toBeVisible();
    await user.click(screen.getByRole("button", { name: "Continue to the next verified stage" }));
    expect(await screen.findByText("Verified loadout ranking")).toBeVisible();
    expect(screen.getByText("+500")).toBeVisible();
    expect(screen.getByRole("combobox", { name: "Result filter" })).toBeVisible();
    expect(screen.getByRole("combobox", { name: "Sort by" })).toBeVisible();
    expect(screen.getByRole("checkbox", { name: "Select rank 1 for comparison" })).toBeVisible();
    await expectNoAutomatedAccessibilityViolations();
    await user.click(screen.getByRole("button", { name: "Export verified Top Gear artifacts" }));
    expect(await screen.findByText(/Exported 5 files/)).toBeVisible();
  });
});
