//! UI-independent application boundary for preparing and executing Quick Sim runs.

use std::{path::Path, time::Duration};

use serde::{Deserialize, Serialize};
use simc_adapter::{HeadlessRunRequest, HeadlessRunResult, run_headless_quick};
use simshredder_domain::{Profile, SourceKind};
use simshredder_job_runner::{
    BatchInput, CpuPlan, CpuPreset, EnqueueRequest, EnqueuedJob, PersistentQueue, apply_cpu_preset,
};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum Error {
    #[error("profile parsing failed: {0}")]
    Parse(#[from] profile_parser::ParseError),
    #[error("input generation failed: {0}")]
    Build(#[from] input_builder::BuildError),
    #[error("SimulationCraft adapter failed: {0}")]
    Adapter(#[from] simc_adapter::Error),
    #[error("persistent runner failed: {0}")]
    Persistent(#[from] simshredder_job_runner::Error),
}

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InputFormat {
    AddonExport,
    SimcFile,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreparedRun {
    pub profile: Profile,
    pub source_bytes: Vec<u8>,
    pub generated_bytes: Vec<u8>,
}

pub fn prepare(input: &str, format: InputFormat) -> Result<PreparedRun> {
    let profile = match format {
        InputFormat::AddonExport => profile_parser::parse_addon_export(input)?,
        InputFormat::SimcFile => profile_parser::parse_simc_file(input)?,
    };
    prepare_profile(input.as_bytes(), profile)
}

pub fn prepare_profile(source_bytes: &[u8], profile: Profile) -> Result<PreparedRun> {
    let generated_bytes = input_builder::build_input(&profile)?;
    Ok(PreparedRun {
        profile,
        source_bytes: source_bytes.to_vec(),
        generated_bytes,
    })
}

pub fn prepare_with_cpu(
    input: &str,
    format: InputFormat,
    preset: CpuPreset,
    logical_cpus: usize,
) -> Result<(PreparedRun, CpuPlan)> {
    let mut profile = match format {
        InputFormat::AddonExport => profile_parser::parse_addon_export(input)?,
        InputFormat::SimcFile => profile_parser::parse_simc_file(input)?,
    };
    let plan = apply_cpu_preset(&mut profile, preset, logical_cpus);
    Ok((prepare_profile(input.as_bytes(), profile)?, plan))
}

pub fn enqueue_persistent(
    queue: &mut PersistentQueue,
    prepared: &PreparedRun,
    executable: &Path,
    expected_revision: &str,
    cpu_preset: CpuPreset,
    timeout: Duration,
) -> Result<EnqueuedJob> {
    Ok(queue.enqueue(EnqueueRequest {
        profile: &prepared.profile,
        batches: vec![BatchInput {
            source_kind: prepared.profile.source_kind,
            source_bytes: prepared.source_bytes.clone(),
            generated_bytes: prepared.generated_bytes.clone(),
        }],
        executable,
        expected_revision,
        cpu_preset,
        timeout,
        rule_revision: simshredder_job_runner::QUICK_RULE_REVISION,
    })?)
}

pub fn execute(
    prepared: &PreparedRun,
    executable: &Path,
    expected_revision: &str,
    output_directory: &Path,
    timeout: Duration,
) -> Result<HeadlessRunResult> {
    Ok(run_headless_quick(HeadlessRunRequest {
        executable,
        expected_revision,
        source_kind: prepared.profile.source_kind,
        source_bytes: &prepared.source_bytes,
        generated_bytes: &prepared.generated_bytes,
        output_directory,
        timeout,
    })?)
}

pub const fn source_kind(format: InputFormat) -> SourceKind {
    match format {
        InputFormat::AddonExport => SourceKind::AddonExport,
        InputFormat::SimcFile => SourceKind::SimcFile,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prepares_a_complete_headless_input() {
        let prepared = prepare(
            "warrior=Core\nlevel=90\nrace=orc\nrole=attack\nspec=fury\nload_default_gear=1\n",
            InputFormat::SimcFile,
        )
        .unwrap();
        assert_eq!(prepared.profile.name, "Core");
        assert!(
            prepared
                .generated_bytes
                .starts_with(b"# Generated by SimShredder\n")
        );
        assert_eq!(source_kind(InputFormat::SimcFile), SourceKind::SimcFile);
    }

    #[test]
    fn persistent_preparation_applies_the_cpu_plan_before_building() {
        let (prepared, plan) = prepare_with_cpu(
            "warrior=Core\nlevel=90\nrace=orc\nrole=attack\nspec=fury\nload_default_gear=1\n",
            InputFormat::SimcFile,
            CpuPreset::Balanced,
            10,
        )
        .unwrap();
        assert_eq!(plan.threads, 4);
        assert!(
            String::from_utf8(prepared.generated_bytes)
                .unwrap()
                .contains("threads=4\n")
        );
    }
}
